vich_uploader:
    db_driver: orm

    mappings:
        attachment:
            uri_prefix: /uploads/attachments
            upload_destination: '%kernel.project_dir%/public/uploads/attachments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_property: updatedAt
            delete_on_update: true
            delete_on_remove: true
        profile_image:
            uri_prefix: /images/profile
            upload_destination: '%kernel.project_dir%/public/uploads/profile'
            namer: Vich\UploaderBundle\Naming\HashNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_property: updatedAt
            delete_on_update: true
            delete_on_remove: true